CREATE TABLE TREE 
(id int,
p_id int);
INSERT INTO TREE (id)VALUES (1)
INSERT INTO TREE VALUES (2,1)
INSERT INTO TREE VALUES (3,1)
INSERT INTO TREE VALUES (4,2)
INSERT INTO TREE VALUES (5,2)

CREATE TABLE TREE_2
(id int,
p_id int);
INSERT INTO TREE_2 (id)VALUES (1)
INSERT INTO TREE_2 VALUES (2,1)
INSERT INTO TREE_2 VALUES (3,1)
INSERT INTO TREE_2 VALUES (4,2)
INSERT INTO TREE_2 VALUES (5,2)

SELECT * FROM TREE;
SELECT * FROM TREE_2;


SELECT id
,CASE WHEN p_id IS NULL THEN 'Root'
      WHEN p_id IS NOT NULL AND id IN (SELECT DISTINCT p_id FROM TREE) THEN 'Inner'
      ELSE 'Leaf'
  END AS type
FROM TREE;